# Generated by Django 5.0.4 on 2024-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('fullname', models.CharField(max_length=30, verbose_name='نام ونام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('phone_number', models.IntegerField(verbose_name='شماره تلفن')),
                ('codeID', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد ملی')),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('profile', models.ImageField(default='static/profile/22_Profile.jpg', upload_to='media', verbose_name='عکس پروفایل')),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'حساب کاربری دانش آموز',
                'verbose_name_plural': 'حساب های کاربری دانش آموزان',
            },
        ),
        migrations.CreateModel(
            name='UserTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, verbose_name='نام ونام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل')),
                ('phone_number', models.IntegerField(verbose_name='شماره تلفن')),
                ('profile', models.ImageField(default='static/profile/22_Profile.jpg', upload_to='media', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'حساب کاربری استاد',
                'verbose_name_plural': 'حساب های کاربری اساتید',
            },
        ),
    ]
